#spring:
#    datasource:
#        username: user
#        password: pass
#        url: jdbc:mysql://172.20.0.2:3306/demodb
#        driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#        show-sql: true
#        hibernate:
#            ddl-auto: update
#        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect